### ISSUE TITLE
DXX-Raytracer 1.1.0 Checklist

### ISSUE THREAD

**Issue by Contingencyy** [BredaUniversityGames/DXX-Raytracer#13]
- [x] NVIDIA crash fix on latest drivers (~December 2023)
- [x] DXR Inline Raytracing
- [x] AMD FSR 2.2 integration & quality modes
- [x] Increased 200 FPS hard lock in player config to 999 FPS
- [x] Tangents for texture overlays fix (community)
- [x] Level geometry sometimes wrongly rotated fix (community)
- [x] Texture compression with DDS files (adapt community implementation)
- [x] Test DDS texture compression (especially super transparency, emissive, overlays)
- [x] Overhaul options menu to be clearer to use
- [x] Change back buffer count from 3 to 2 to reduce input lag a little bit
- [x] Test AMD FSR with low FPS for ghosting
- [x] Add output & render resolution to render debug menu
- [x] Add FPS and frame time to render debug menu
- [x] Check all materials for proper FSR2 reactive mask flags
- [x] Test debug, release, and ship builds (both with DispatchRays and Inline)
- [x] Prepare post (mention that without upscaling TAA is the better option)
- [ ] Add guidelines for pull requests (reference images, testing, etc.)
- [x] Release 1.1.0
- [ ] Post post on Discord, but probably also Reddit and YouTube since the NVIDIA issue is very consistent on all cards with latest drivers

**Comment by SamBoots** [comment]
So these seem to be all good right?
